name: Go

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # OSes to run on
        version: [1.19] # Go version to use

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} Go ${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}

      - name: Build (Directories)
        run: mkdir build

      - name: Bulid (Binary)
        run: go build -o build/wiki ./main.go

      - name: Bulid (Debian)
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: make deb

      - name: Rename binary for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: move build/wiki build/wiki.exe

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: Wiki CLI - ${{ matrix.os }}
          path: ./build
